//notes on playwright


/*
WHAT IS PLAYWRIGHT?

A FRAMEWORK DESIGN TO PROVIDE RELIABLE END TO END TESTING


INSTALLING PLAYWRIGHT THROUGH VS CODE:

USING THE PLAYWRIGHT EXTENSION PROVIDED BY MICROSOFT WE CAN RUN THE COMMAND "INSTALL PLAYWRIGHT".


*/
